# Generated by Django 4.1.5 on 2023-01-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostoapp', '0002_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
